import './global.css';
import { color } from '@nexpo/ui-tokens';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={color.background.light}>
      <body>{children}</body>
    </html>
  );
}
